services:
  keycloak_postgres:
    container_name: keycloak_postgres
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_net

  keycloak:
    container_name: keycloak_app
    image: quay.io/keycloak/keycloak:latest
    restart: unless-stopped
    ports:
      # - "127.0.0.1:8943:8443"
      - "127.0.0.1:8015:8080"
    environment:
      # Admin user for the admin console (change for production)
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_HOSTNAME: ${KEYCLOAK_URL}
      # Database config (Quarkus-based Keycloak uses KC_... envs)
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_postgres:5432/keycloak
      KC_DB_USERNAME:  ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    # volumes:
      # - "./certs/keycloak.local.crt:/opt/keycloak/conf/keycloak.local.crt" # map certificates to container
      # - "./certs/keycloak.local.key:/opt/keycloak/conf/keycloak.local.key" # map certificates to container
    depends_on:
      - keycloak_postgres
    networks:
      - keycloak_net
    command:
      - start-dev


networks:
  keycloak_net:
    name: keycloak_net
    driver: bridge

volumes:
  postgres_data: