services:
  keycloak_postgres:
    image: postgres:15
    container_name: keycloak_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_net
      - ext-net

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_app
    restart: unless-stopped
    ports:
      # - "8015:8080" # Hide HTTP port
      - "18743:8443" # Expose the HTTPS port
    environment:
      # Admin user for the admin console (change for production)
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_HOSTNAME: ${KEYCLOAK_URL}
      # Specify the files within the container's filesystem
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/certs/keycloak.local.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/certs/keycloak.local.key
      # Database config (Quarkus-based Keycloak uses KC_... envs)
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_postgres:5432/keycloak
      KC_DB_USERNAME:  ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "./certs:/opt/keycloak/conf/certs:ro"
    command:
      - start-dev
    depends_on:
      - keycloak_postgres
    networks:
      - keycloak_net
      - ext-net

networks:
  keycloak_net:
    name: keycloak_net
    driver: bridge
  ext-net:
    name: shared-ext-net # External network to connect containers across different compose projects 
    external: true

volumes:
  postgres_data: